contact_email: ssl@7.fr 

defaults:
  distinguished_name:
    country: FR
    locality: Paris
    organization_name: 7 Medical
  solver: http

certificates:
  - domain: api.ph.fr
    distinguished_name:
      organization_name: Test PH
      organization_unit_name: api-ph-fr
      locality: 'github.com:Solutions-PH/api.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/api-ph-fr
  - domain: lrs.ph.fr
    distinguished_name:
      organization_name: LRS PH
      organization_unit_name: lrs-ph-fr
      locality: 'github.com:Solutions-PH/lrs.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/lrs-ph-fr      
  - domain: expert.ph.fr
    distinguished_name:
      organization_name: Plateforme Expert Opsharm
      organization_unit_name: expert-ph-fr
      locality: 'github.com:Ospharea/expert.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/expert-ph-fr
  - domain: sentinel.ph.fr
    distinguished_name:
      organization_name: Plateforme Sentinel ID
      organization_unit_name: sentinel-ph-fr
      locality: 'github.com:Solutions-PH/sentinel.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/sentinel-ph-fr
  - domain: www.looksante.fr
    distinguished_name:
      organization_name: Looksante
      organization_unit_name: www-looksante-fr
      locality: 'github.com:Solutions-PH/looksante.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/www-looksante-fr