contact_email: ssl@7.fr 

defaults:
  distinguished_name:
    country: FR
    locality: Paris
    organization_name: 7 Medical
  solver: http

certificates:
  - domain: forum.ospharm.org
    distinguished_name:
      organization_name: Forum Ospharm
      locality: 'github.com:ospharea/forum.git'
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/forum-ospharm-org/public
