contact_email: ssl@7.fr 

defaults:
  distinguished_name:
    country: FR
    locality: Paris
    organization_name: 7 Medical
  solver: http

certificates:
  - domain: bi.7.fr
    distinguished_name:
      organization_name: BI 7.fr
      organization_unit_name: bi-7-fr
    solver:
      name: http-file
      adapter: local
      root: /var/www/bi-7-fr
