contact_email: ssl@7.fr 

defaults:
  distinguished_name:
    country: FR
    locality: Paris
    organization_name: 7 Medical
  solver: http

certificates:
  - domain: test.ph.fr
    path: test-ph-fr
    distinguished_name:
      organization_name: Test PH
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/test-ph-fr
  - domain: test2.ph.fr
    path: test2-ph-fr
    distinguished_name:
      organization_name: Test PH
    solver:
      name: http-file
      adapter: local
      root: /var/www/webroot/test2-ph-fr